#!/usr/bin/env bash
# Install `markdown-to-pdf` onto $PATH as a real executable.
#
# Creates (or repairs) a private virtualenv beside this script, installs the
# runtime dependencies into it, and writes a small launcher at
# $BIN_DIR/markdown-to-pdf that runs the converter with that interpreter — so
# the tool is a real command reachable by any shell, script, or tool, not just
# an interactive shell.
#
# Re-running refreshes the virtualenv and OVERWRITES the launcher in place, so
# this doubles as the updater and never leaves a second copy behind. Safe to run
# directly from a clone; it resolves its own directory and hardcodes no
# machine-specific path.
set -euo pipefail

usage() {
  cat <<'EOF'
install.sh — install markdown-to-pdf onto $PATH as a real executable.

Usage:
  ./install.sh [--help]

Options:
  -h, --help   Print this help and exit.

Environment:
  BIN_DIR      Directory to install the `markdown-to-pdf` launcher into.
               Created if missing. Default: $HOME/.local/bin.

Examples:
  ./install.sh                      # install to ~/.local/bin/markdown-to-pdf
  BIN_DIR=/usr/local/bin ./install.sh   # install elsewhere on $PATH
  ./install.sh && markdown-to-pdf chapter.md   # install, then convert a file
EOF
}

case "${1:-}" in
  -h | --help)
    usage
    exit 0
    ;;
  "") ;;
  *)
    usage >&2
    exit 1
    ;;
esac

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

# Where to install the launcher. Callers may pass BIN_DIR; otherwise default to
# the conventional user bin dir. Resolved to an absolute path so the $PATH check
# below compares like with like.
BIN_DIR="${BIN_DIR:-$HOME/.local/bin}"
mkdir -p "$BIN_DIR"
BIN_DIR="$(cd -- "$BIN_DIR" && pwd)"

VENV="$SCRIPT_DIR/.venv"
PY="$VENV/bin/python"

# A virtualenv is bound to the interpreter it was built from, so an upgraded,
# switched, or removed Python leaves it dangling. Rebuild it whenever its
# interpreter no longer runs, which makes a broken install self-healing.
if [ ! -x "$PY" ] || ! "$PY" -c '' >/dev/null 2>&1; then
  command -v python3 >/dev/null 2>&1 || {
    echo "error: python3 not found; install Python 3 first" >&2
    exit 1
  }
  echo "Creating virtualenv at ${VENV}…" >&2
  rm -rf "$VENV"
  if ! python3 -m venv "$VENV" >&2; then
    echo "error: 'python3 -m venv' failed." >&2
    echo "       On Debian/Ubuntu the venv module ships separately:" >&2
    echo "         sudo apt install python3-venv" >&2
    exit 1
  fi
fi

# Needs network the first time (and whenever requirements.txt changes); pip
# resolves offline once everything is already satisfied.
echo "Installing dependencies…" >&2
"$PY" -m pip install --quiet --disable-pip-version-check -r "$SCRIPT_DIR/requirements.txt" >&2
"$PY" -c 'import reportlab' || {
  echo "error: dependencies did not install correctly into $VENV" >&2
  exit 1
}

# Fixed filename, so each run overwrites the previous launcher instead of adding
# another one. It execs run.sh, which keeps the CLI defined in exactly one place
# and picks up pulled code with no reinstall.
LAUNCHER="$BIN_DIR/markdown-to-pdf"
cat >"$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Generated by markdown-to-pdf's install.sh — do not edit; re-run install.sh.
#
# The converter and its virtualenv stay in the clone this was installed from, so
# keep that clone around; if you move it, re-run its install.sh.
set -euo pipefail
RUN_SH="$SCRIPT_DIR/run.sh"
if [ ! -x "\$RUN_SH" ]; then
  echo "error: markdown-to-pdf is not where it was installed from (\$RUN_SH)." >&2
  echo "       The clone was moved or deleted — re-run install.sh from it." >&2
  exit 1
fi
exec "\$RUN_SH" "\$@"
EOF
chmod 0755 "$LAUNCHER"

echo "installed markdown-to-pdf -> $LAUNCHER"

# A launcher nobody can invoke is not an install. Say so, with the fix.
case ":${PATH}:" in
  *":$BIN_DIR:"*) ;;
  *)
    echo >&2
    echo "note: $BIN_DIR is not on your \$PATH, so \`markdown-to-pdf\` won't be found yet." >&2
    echo "      Add it to your shell startup file, e.g.:" >&2
    echo "        echo 'export PATH=\"$BIN_DIR:\$PATH\"' >> ~/.zshrc   # or ~/.bashrc" >&2
    ;;
esac
